### ISSUE TITLE
Datasette packages are missing the plugin hook registration

### ISSUE THREAD

**Issue by simonw** [asg017/sqlite-dist#9]
Refs:
- https://github.com/asg017/sqlite-vec/issues/60

Relevant code:

https://github.com/asg017/sqlite-dist/blob/f4e43b3a708e23fde716fc2cb04123fc1ff1f522/src/pip.rs#L316

**Comment by simonw** [comment]
To replicate:
```bash
datasette install datasette-sqlite-vec
datasette plugins
```
This should show that the plugin is installed, but it doesn't.

A working plugin looks like this in `site-packages`:

```
cat datasette_secrets-0.2.dist-info/entry_points.txt
```
```
[datasette]
secrets = datasette_secrets
```
But `datasette_sqlite_vec-0.1.0.dist-info/entry_points.txt` is missing.

**Comment by asg017** [comment]
Can confirm, the __init__.py is wonky:

```py

from datasette import hookimpl
import datasette_sqlite_vec

__version__ = "0.1.0"
__version_info__ = tuple(__version__.split("."))

@hookimpl
def prepare_connection(conn):
  conn.enable_load_extension(True)
  datasette_sqlite_vec.load(conn)
  conn.enable_load_extension(False)
```

That `datasette_sqlite_vec` should be `sqlite_vec`, will fix shortly

**Comment by simonw** [comment]
I think what's missing is this generated `setup.py` line: https://github.com/asg017/sqlite-vector/blob/1fdc48a773808392fe0776b66c4ac0aa2d18a068/python/datasette_sqlite_vector/setup.py#L20

```python
    entry_points={"datasette": ["sqlite_vector = datasette_sqlite_vector"]},
```
That's from the older `datasette-sqlite-vector` plugin.

**Comment by asg017** [comment]
For now the workaround can be installing the sqlite-vec python package and writing a custom Datasette plugin:

```py

from datasette import hookimpl
import sqlite_vec

@hookimpl
def prepare_connection(conn):
  conn.enable_load_extension(True)
  sqlite_vec.load(conn)
  conn.enable_load_extension(False)
```

**Comment by simonw** [comment]
This workaround works too:

```bash
datasette --load-extension "$(python -c 'print(__import__("sqlite_vec").loadable_path())')"
```
Suggestion: make it so the following outputs the path:

```bash
python -m sqlite_vec
```
That way the above recipe could look like this instead:
```bash
datasette --load-extension "$(python -m sqlite_vec)"
```

**Comment by asg017** [comment]
Fixed in this release: https://github.com/asg017/sqlite-dist/releases/tag/v0.0.1-alpha.9
